refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean. The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.
```
Error details for reference:
gate/gate-basic/src/main/java/com/netflix/spinnaker/gate/security/basic/BasicAuthConfig.java:29: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
                                                                       ^
  symbol:   class WebSecurityConfigurerAdapter
```

Reference:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter