refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.
```
Attached a portion of error logs for reference:
gate/gate-x509/src/main/java/com/netflix/spinnaker/gate/security/x509/X509IdentityExtractor.java:6: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;

```

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee