refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.
```
Attached a portion of error logs for reference:
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/ResponseHeaderInterceptor.java:23: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java:36: error: package javax.servlet does not exist
import javax.servlet.FilterChain;
                    ^
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java:37: error: package javax.servlet does not exist
import javax.servlet.ServletException;
                    ^
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java:38: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpFilter;
                         ^
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java:39: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
                         ^
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/ratelimit/RateLimitingFilter.java:40: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletResponse;
```

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee