refactor(dependency): replace HandlerInterceptorAdapter with HandlerInterceptor during upgrade of spring boot 3.0.x
Since `org.springframework.web.servlet.handler.HandlerInterceptorAdapter` has been deprecated in springframework 5.3.0 and removed in 6, replacing it with `org.springframework.web.servlet.HandlerInterceptor`.
```
Attached a portion of error logs for reference:
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/RequestContextInterceptor.java:24: error: cannot find symbol
import org.springframework.web.servlet.handler.HandlerInterceptorAdapter;
gate/gate-web/src/main/groovy/com/netflix/spinnaker/gate/interceptors/ResponseHeaderInterceptor.java:25: error: cannot find symbol
import org.springframework.web.servlet.handler.HandlerInterceptorAdapter;
```

Reference Links:
https://github.com/spring-projects/spring-framework/pull/25147