refactor: Updated the test case expectation. NestedServletException deprecated as of spring framework 6.0, in favor of standard ServletException.
Error:
WebhooksControllerSpec > handles CDEvents API server Ping FAILED
    Expected exception of type 'org.springframework.web.util.NestedServletException', but got 'jakarta.servlet.ServletException'
        at app//org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:95)
        at app//org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:74)
        at com.netflix.spinnaker.gate.controllers.WebhooksControllerSpec.handles CDEvents API server Ping(WebhookControllerSpec.groovy:154)

        Caused by:
        jakarta.servlet.ServletException: Request processing failed: retrofit.RetrofitError: Failed to connect to localhost/127.0.0.1:45135
            at app//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1022)
            at app//org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
            at app//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
            at app//org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
            at app//org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:72)
            at app//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
            at app//org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:165)
            at app//org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
            at app//org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:201)
            at com.netflix.spinnaker.gate.controllers.WebhooksControllerSpec.handles CDEvents API server Ping(WebhookControllerSpec.groovy:150)

            Caused by:
            retrofit.RetrofitError: Failed to connect to localhost/127.0.0.1:45135
                at app//retrofit.RetrofitError.networkError(RetrofitError.java:27)
                at app//retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
                at app//retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                at com.netflix.spinnaker.gate.services.WebhookService.webhooks_closure3(WebhookService.groovy:61)
                at com.netflix.spinnaker.gate.services.WebhookService.webhooks_closure3(WebhookService.groovy)
                at app//com.netflix.spinnaker.security.AuthenticatedRequest.allowAnonymous(AuthenticatedRequest.java:137)
                at app//com.netflix.spinnaker.gate.services.WebhookService.webhooks(WebhookService.groovy:60)
                at app//com.netflix.spinnaker.gate.controllers.WebhookController.webhooks(WebhookController.groovy:62)
                at app//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
                at app//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
                at app//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
                at app//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
                at app//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
                at app//org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
                at app//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
                at app//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
                at app//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
                ... 9 more

                Caused by:
                java.net.ConnectException: Failed to connect to localhost/127.0.0.1:45135
                    at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
                    at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
                    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
                    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                    at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:41)
                    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                    ... 24 more

                    Caused by:
                    java.net.ConnectException: Connection refused
                        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
                        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
                        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
                        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
                        at java.base/java.net.Socket.connect(Socket.java:633)
                        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                        ... 41 more
 Reference:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/NestedServletException.html