refactor(security): Updated deprecated/removed Spring Security methods for compatibility with version 6.
Replaced the following methods:

 1. authorizeRequests with authorizeHttpRequests
 2. requestMatcher with securityMatcher
 3. antMatchers with requestMatchers
These updates address deprecations introduced in Spring Security 5.8, as some of these methods were removed in Spring Security 6. This ensures compatibility and resolves related errors.

Error details for reference:

text
Copy code
gate/gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java:75: error: cannot find symbol
    http.requestMatcher(requestMatcherProvider.requestMatcher())
        ^
  symbol:   method requestMatcher(RequestMatcher)
  location: variable http of type HttpSecurity

gate/gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java:89: error: cannot find symbol
                  .antMatchers("/error")
                  ^
  symbol:   method antMatchers(String)
  location: variable registry of type ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry

gate/gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java:101: error: cannot find symbol
              var webhooks = registry.antMatchers(HttpMethod.POST, "/webhooks/**");
                                     ^
  symbol:   method antMatchers(HttpMethod,String)
  location: variable registry of type ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry

gate/gate-core/src/main/java/com/netflix/spinnaker/gate/config/AuthConfig.java:108: error: cannot find symbol
                  .antMatchers(HttpMethod.POST, "/notifications/callbacks/**")
                  ^
  symbol:   method antMatchers(HttpMethod,String)
  location: variable registry of type ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry
Reference:
https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#use-new-security-matchers