refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean. The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.
```
Attached a portion of error logs for reference:
gate/gate-x509/src/main/java/com/netflix/spinnaker/gate/security/x509/X509Config.java:32: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
gate/gate-web/src/main/java/com/netflix/spinnaker/gate/config/ManagedDeliverySchemaEndpointConfiguration.java:24: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
```

Reference Links:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter