refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean. The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.
Error details for reference:
```
gate/gate-core/src/main/java/com/netflix/spinnaker/gate/security/anonymous/AnonymousConfig.java:52: error: cannot find symbol
public class AnonymousConfig extends WebSecurityConfigurerAdapter {
                                     ^
  symbol: class WebSecurityConfigurerAdapter
```
Reference:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter