refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean. The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.
```
Error details for reference:
gate/gate-saml/src/main/java/com/netflix/spinnaker/gate/security/saml/SAMLConfiguration.java:36: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
gate/gate-iap/src/main/java/com/netflix/spinnaker/gate/security/iap/IapSsoConfig.java:36: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
                                                                       ^
  symbol:   class WebSecurityConfigurerAdapter
  location: package org.springframework.security.config.annotation.web.configuration
```

Reference:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter